package br.com.afirmanet.questions.enums;


public enum TypeServicoEnum {
	RETRIEVE_AND_RANK,
	TRADE_OFF_ANALYTICS,
	ALCHEMY_LANGUAGE,
	RELATIONSHIP_EXTRATION,
	TONY_ANALAISER,
	DEVELOP_CLOUD,
	PERSOLALITY_INSIGHTS,
	ALCHAMYAPI,
	SENTIMENT_ANALYSIS,
	DOCUMENT_CONVERSION,
	CONCEPT_INSIGHTS,
	VISUAL_RECOGNITION,
	FACE_DETECTION,
	NATURAL_LANGUAGE_CLASSIFIER,
	TEXT_TO_SPEECH,
	SPEECH_TO_TEXT,
	DIALOG;
}
